### ISSUE TITLE
Possible bug in ListFiles when dealing with ico files

### ISSUE THREAD

**Issue by prabhuteja12** [artmoskvin/hide#101]
Hi!

I have a project that contains a few .ico files, and creating the project files with them causes the error 

```
Error reading file /doc/_static/favicon_old.ico: Failed to create lines from content: bufio.Scanner:
 token too long" projectId=...
```
I got around this by adding `ignorePatterns = append(ignorePatterns, "*.ico")` but I guess this needs to be fixed differently. The same project has a both of svg, pngs but they don't seem to cause any issues. 

I don't know any Go to suggest fixes for this. But reporting this hoping that this is a simple fix. 

Thanks!

**Comment by artmoskvin** [comment]
Hi! Thanks for reporting, I'm looking at it now.

**Comment by prabhuteja12** [comment]
Thank you for the quick fix!

**Comment by artmoskvin** [comment]
@prabhuteja12 thanks again for reporting it! Let us know how it works. The current solution is more like a hotfix. We'll plan for a better solution tomorrow.

**Comment by artmoskvin** [comment]
@prabhuteja12 btw I started a Discord server today if you need more help or just want to chat :) https://discord.gg/xPqnDpjm
