### ISSUE TITLE
Bug in List files when reading some non-standard files

### ISSUE THREAD

**Issue by prabhuteja12** [artmoskvin/hide#105]
Similar to #101 , I found another case when reading `astropy`. Here is the traceback. 

```
line 144, in list_files
    raise HideClientError(response.text)
hide.client.hide_client.HideClientError: Failed to list files: Failed to list files in project onDDqHYnHh: Error reading file /astropy/io/fits/tests/data/o4sp040b0_raw.fits: Failed to create lines from content: bufio.Scanner: token too long
```

Thank you!

**Comment by artmoskvin** [comment]
Thanks for reporting! We were just working on a proper fix this morning https://github.com/artmoskvin/hide/pull/106. I'll test run it on `astropy` now.

**Comment by aleh-null** [comment]
@prabhuteja12 fix is merged, we also tested it with `astropy` and it's looking good. Please take a look and let us know if you have more issues.

**Comment by prabhuteja12** [comment]
@aleh-null Indeed! My previously failing cases are working now. Thank you!
